### ISSUE TITLE
Why not use mozilla/webrtc-sdp crate?

### ISSUE THREAD

**Issue by isqad** [webrtc-rs/sdp#7]
Hi! I see you re-wrote pion/sdp to Rust, but why do you not used well formed [mozilla/webrtc-sdp](https://github.com/mozilla/webrtc-sdp) crate?

**Comment by rainliu** [comment]
The API of mozilla/webrtc-sdp crate may not be suitable for webrtc-rs stack, since webrtc-rs is aligned with Pion's API design.
